services:
  front:
    build:
      context: front
      dockerfile: dockerfile
    container_name: front
    ports:
      - 8080:8080
    links:
      - api
  api:
    build:
      context: api
      dockerfile: dockerfile
    container_name: api
    ports:
      - 4200:80