FROM node:20 AS build

#RUN apt-get update \
#&& apt-get install -y -f nodejs \
#&& apt-get install -y -f npm \
#&& apt-get install -y -f git \
#&& npm ci
#&& npm install -g @angular/cli \
#&& npm install --only=production

WORKDIR /doodlestudent

COPY . .

EXPOSE 4200 8080

#RUN git clone https://github.com/barais/doodlestudent.git --depth 1

RUN npm install

RUN npm run build --prod

FROM nginx

COPY --from=build /doodlestudent/dist/tlcfront/ /usr/share/nginx/html
